name: tests-and-package-build
run-name: tests and package build
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - run: uv run pytest
      - run: uv run ruff check
      - run: uv run ruff format